### ISSUE TITLE
http://per.vyrd.net/ has been down for a while.

### ISSUE THREAD

**Issue by im-grey** [bibanon/bibanon#13]
http://per.vyrd.net/ Was a website that stored a lot of history on it, including the whole Nurse-kun story and a lot of Nevada-chan art. I noticed it went offline a week or so ago and has not come back. I don't know where else to ask. Is there an archive of it anywhere?

**Comment by antonizoon** [comment]
The website operator vyrd was supposed to transfer it over to our servers, but I guess it hasn't happened yet. He did successfully back up the data, I just would not have control over the domain.

Check out vyrd.bibanon.org/per and vyrd.bibanon.org in the meantime.

On September 29, 2017 12:26:35 PM EDT, grey <notifications@github.com> wrote:
>http://per.vyrd.net/ Was a website that stored a lot of history on it,
>including the whole Nurse-kun story and a lot of Nevada-chan art. I
>noticed it went offline a week or so ago and has not come back. I don't
>know where else to ask. Is there an archive of it anywhere?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bibanon/bibanon/issues/13

Sincerely,
Antonizoon

**Comment by antonizoon** [comment]
I set the DNS and shit a month ago, no idea what might have happened. I don't have StableHost anymore obv, but that shouldn't have changed anything, let me look at it later.

Also I do owe you for the next month. Haven't forgotten!

**Comment by antonizoon** [comment]
I realized that the server vyrd was being hosted on was offline, and turned it back on. If I had known the domain had already been switched I would have known what to do. Sorry about that.

Vyrd.net is back up.
