### ISSUE TITLE
Shii's wiki archived

### ISSUE THREAD

**Issue by cupboardboard** [bibanon/bibanon#5]
Thankfully, I had downloaded Shii's wiki with HTTrack one day prior the deletion (I had a feeling that it was going to get deleted).
If this helps, here's a zip for the Everything Shii Knows wiki: http://www.mediafire.com/download/u7wlspdkyy1ueyi/shii.zip
And here's a zip of Shii.org World Wide Web History Archive: http://www.mediafire.com/download/f3cwdfq3t3xayj9/shii+wh.zip

**Comment by StrawberrySunshine** [comment]
Sorry to bump this old thread, but I was looking for info on a particular page which is linked in the archive but doesn't seem to have been saved:

It was in the What's New section, listed as "New!! United States Presidential election, 2012":

http://shii.org/mediawiki/index.php?title=United_States_Presidential_election,_2012&action=edit&redlink=1

But it's not been saved in the internet archive or anywhere else, as far as I can tell. Does anyone know anything about it?

**Comment by antonizoon** [comment]
Technically we are failing to abide by the author's wishes by continuing to archive any pages much like Emily Dickinson,. So you could try to reach out to him but he seems a bit ashamed of all this dark angsty teen history from what I feel. The robots.txt on this site specifically blocked all crawlers and archive.org abided by it, so there is no other scrape. As for the page, I suppose it was linked but was unfinished at the time as per the structure of the link? I don't remember if it was ever finished.
